global:
  #Ã„ndra till 30 sekunder minst
  scrape_interval: 30s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["0.0.0.0:9090"]
  - job_name: "alertmanager"
    static_configs:
      - targets: ["0.0.0.0:9093"]



  - job_name: "app"
    static_configs:
      - targets: ["https://micro-blog.tech:8000"]
